name: Flutter CI/CD Workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.16.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Create Keystore file
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: $KEYSTORE_FILE

      - name: Set Keystore Path
        run: echo "KEYSTORE_PATH=${{ steps.android_keystore.outputs.filePath }}" >> $GITHUB_ENV

      - name: Build appbundle
        run: flutter build appbundle
