name: Flutter CI/CD Workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEYSTORE_PATH: "android/app/keystore.jks"

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.16.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Create Keystore file
        run: echo $KEYSTORE_FILE | base64 -di > android/app/keystore.jks

      - name: Build appbundle
        run: flutter build appbundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/bundle/

  deploy-to-staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: echo "Deploying to staging environment..."
