name: Flutter CI/CD Workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      PROPERTIES_PATH: "./android/key.properties"

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.16.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Creating Key.properties file
        run: |
          echo keyPassword=\${{ secrets.KEYSTORE_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEYSTORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}

      - name: Create Keystore file
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/key.jks

      - name: Build appbundle
        working-directory: android
        run: flutter build appbundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/bundle/

  deploy-to-staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: echo "Deploying to staging environment..."
