name: Flutter CI/CD Workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.16.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/apk/release/
